# Generated by Django 4.1.3 on 2022-11-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_user_flat'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='house_index',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
