# Generated by Django 4.1.3 on 2022-11-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_house_house_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='flat',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
